In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df1 = pd.read_csv('chennai_real_estate_data.csv')

In [3]:
df1

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Carpet Area,Ready To Move,Anna Nagar,1 BHK,Society1,1117,2,0,49.91
1,Carpet Area,Under Construction,Anna Nagar,4 BHK,Society3,3725,4,0,101.91
2,Plot Area,Ready To Move,Adyar,2 BHK,Society1,1915,1,3,90.78
3,Carpet Area,Ready To Move,Velachery,2 BHK,Society1,2308,2,3,132.87
4,Carpet Area,Under Construction,Tambaram,3 BHK,Society5,2526,3,2,70.73
...,...,...,...,...,...,...,...,...,...
4995,Carpet Area,Ready To Move,Medavakkam,4 BHK,Society1,2144,4,3,131.00
4996,Plot Area,Ready To Move,Velachery,5 BHK,Society4,3288,4,0,135.49
4997,Carpet Area,Under Construction,Thiruvanmiyur,1 BHK,Society4,615,2,1,20.86
4998,Carpet Area,Under Construction,Medavakkam,3 BHK,Society1,1569,2,2,90.90
4999,Carpet Area,Under Construction,T. Nagar,1 BHK,Society5,797,1,0,22.52

# Data Cleaning

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     5000 non-null   object
 1   availability  5000 non-null   object
 2   location      5000 non-null   object
 3   size          5000 non-null   object
 4   society       5000 non-null   object
 5   total_sqft    5000 non-null   int64
 6   bath          5000 non-null   int64
 7   balcony       5000 non-null   int64
 8   price         5000 non-null   float64
dtypes: float64(1), int64(3), object(5)
memory usage: 351.7+ KB

In [5]:
df1.describe()

        total_sqft         bath      balcony        price
count  5000.000000  5000.000000  5000.000000  5000.000000
mean   2556.474200     2.400600     1.508600   121.464538
std    1364.658724     1.266349     1.110573    75.037440
min     502.000000     1.000000     0.000000    13.820000
25%    1374.750000     1.000000     1.000000    61.982500
50%    2354.000000     2.000000     1.000000   107.150000
75%    3486.000000     3.000000     3.000000   164.720000
max    5993.000000     5.000000     3.000000   400.790000

In [6]:
df1.isnull().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [7]:
df1.shape

(5000, 9)

In [8]:
df2 = df1.drop (['area_type', 'society','balcony','availability'], axis = 'columns')
df2

           location   size  total_sqft  bath   price
0        Anna Nagar  1 BHK        1117     2   49.91
1        Anna Nagar  4 BHK        3725     4  101.91
2             Adyar  2 BHK        1915     1   90.78
3         Velachery  2 BHK        2308     2  132.87
4          Tambaram  3 BHK        2526     3   70.73
...             ...    ...         ...   ...     ...
4995     Medavakkam  4 BHK        2144     4  131.00
4996      Velachery  5 BHK        3288     4  135.49
4997  Thiruvanmiyur  1 BHK         615     2   20.86
4998     Medavakkam  3 BHK        1569     2   90.90
4999       T. Nagar  1 BHK         797     1   22.52

[5000 rows x 5 columns]

In [9]:
df2['size'].unique()

array(['1 BHK', '4 BHK', '2 BHK', '3 BHK', '5 BHK'], dtype=object)

In [10]:
df2['bhk'] = df2['size'].apply(lambda x: int(x.split(' ')[0]))
df2.head()

     location   size  total_sqft  bath   price  bhk
0  Anna Nagar  1 BHK        1117     2   49.91    1
1  Anna Nagar  4 BHK        3725     4  101.91    4
2       Adyar  2 BHK        1915     1   90.78    2
3   Velachery  2 BHK        2308     2  132.87    2
4    Tambaram  3 BHK        2526     3   70.73    3

In [11]:
df2.drop("size" ,axis="columns")

           location  total_sqft  bath   price  bhk
0        Anna Nagar        1117     2   49.91    1
1        Anna Nagar        3725     4  101.91    4
2             Adyar        1915     1   90.78    2
3         Velachery        2308     2  132.87    2
4          Tambaram        2526     3   70.73    3
...             ...         ...   ...     ...  ...
4995     Medavakkam        2144     4  131.00    4
4996      Velachery        3288     4  135.49    5
4997  Thiruvanmiyur         615     2   20.86    1
4998     Medavakkam        1569     2   90.90    3
4999       T. Nagar         797     1   22.52    1

[5000 rows x 5 columns]

In [12]:
dummies = pd.get_dummies(df2.location)
dummies

,Adyar,Anna Nagar,Kodambakkam,Medavakkam,Nungambakkam,Sholinganallur,T. Nagar,Tambaram,Thiruvanmiyur,Velachery
0,False,True,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,True,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,True
4997,False,False,False,False,False,False,False,False,True,False
4998,False,False,False,True,False,False,False,False,False,False
4999,False,False,False,False,False,False,True,False,False,False

In [13]:
dummies_df=dummies.astype(int)
dummies_df

,Adyar,Anna Nagar,Kodambakkam,Medavakkam,Nungambakkam,Sholinganallur,T. Nagar,Tambaram,Thiruvanmiyur,Velachery
0,0,1,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
4995,0,0,0,1,0,0,0,0,0,0
4996,0,0,0,0,0,0,0,0,0,1
4997,0,0,0,0,0,0,0,0,1,0
4998,0,0,0,1,0,0,0,0,0,0
4999,0,0,0,0,0,0,1,0,0,0

In [14]:
merged = pd.concat([df2,dummies],axis='columns')
merged

,location,size,total_sqft,bath,price,bhk,Adyar,Anna Nagar,Kodambakkam,Medavakkam,Nungambakkam,Sholinganallur,T. Nagar,Tambaram,Thiruvanmiyur,Velachery
0,Anna Nagar,1 BHK,1117,2,49.91,1,False,True,False,False,False,False,False,False,False,False
1,Anna Nagar,4 BHK,3725,4,101.91,4,False,True,False,False,False,False,False,False,False,False
2,Adyar,2 BHK,1915,1,90.78,2,True,False,False,False,False,False,False,False,False,False
3,Velachery,2 BHK,2308,2,132.87,2,False,False,False,False,False,False,False,False,False,True
4,Tambaram,3 BHK,2526,3,70.73,3,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Medavakkam,4 BHK,2144,4,131.00,4,False,False,False,True,False,False,False,False,False,False
4996,Velachery,5 BHK,3288,4,135.49,5,False,False,False,False,False,False,False,False,False,True
4997,Thiruvanmiyur,1 BHK,615,2,20.86,1,False,False,False,False,False,False,False,False,True,False
4998,Medavakkam,3 BHK,1569,2,90.90,3,False,False,False,True,False,False,False,False,False,False
4999,T. Nagar,1 BHK,797,1,22.52,1,False,False,False,False,False,False,True,False,False,False

In [15]:
final = merged.drop(['location','size'], axis='columns')
final.astype(int)

,total_sqft,bath,price,bhk,Adyar,Anna Nagar,Kodambakkam,Medavakkam,Nungambakkam,Sholinganallur,T. Nagar,Tambaram,Thiruvanmiyur,Velachery
0,1117,2,49,1,0,1,0,0,0,0,0,0,0,0
1,3725,4,101,4,0,1,0,0,0,0,0,0,0,0
2,1915,1,90,2,1,0,0,0,0,0,0,0,0,0
3,2308,2,132,2,0,0,0,0,0,0,0,0,0,1
4,2526,3,70,3,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2144,4,131,4,0,0,0,1,0,0,0,0,0,0
4996,3288,4,135,5,0,0,0,0,0,0,0,0,0,1
4997,615,2,20,1,0,0,0,0,0,0,0,0,1,0
4998,1569,2,90,3,0,0,0,1,0,0,0,0,0,0
4999,797,1,22,1,0,0,0,0,0,0,1,0,0,0

In [16]:
final = final.drop(['Velachery'], axis='columns')
final.astype(int)

,total_sqft,bath,price,bhk,Adyar,Anna Nagar,Kodambakkam,Medavakkam,Nungambakkam,Sholinganallur,T. Nagar,Tambaram,Thiruvanmiyur
0,1117,2,49,1,0,1,0,0,0,0,0,0,0
1,3725,4,101,4,0,1,0,0,0,0,0,0,0
2,1915,1,90,2,1,0,0,0,0,0,0,0,0
3,2308,2,132,2,0,0,0,0,0,0,0,0,0
4,2526,3,70,3,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2144,4,131,4,0,0,0,1,0,0,0,0,0
4996,3288,4,135,5,0,0,0,0,0,0,0,0,0
4997,615,2,20,1,0,0,0,0,0,0,0,0,1
4998,1569,2,90,3,0,0,0,1,0,0,0,0,0
4999,797,1,22,1,0,0,0,0,0,0,1,0,0

In [17]:
X = final.drop('price', axis='columns')
X.astype(int)

,total_sqft,bath,bhk,Adyar,Anna Nagar,Kodambakkam,Medavakkam,Nungambakkam,Sholinganallur,T. Nagar,Tambaram,Thiruvanmiyur
0,1117,2,1,0,1,0,0,0,0,0,0,0
1,3725,4,4,0,1,0,0,0,0,0,0,0
2,1915,1,2,1,0,0,0,0,0,0,0,0
3,2308,2,2,0,0,0,0,0,0,0,0,0
4,2526,3,3,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2144,4,4,0,0,0,1,0,0,0,0,0
4996,3288,4,5,0,0,0,0,0,0,0,0,0
4997,615,2,1,0,0,0,0,0,0,0,0,1
4998,1569,2,3,0,0,0,1,0,0,0,0,0
4999,797,1,1,0,0,0,0,0,0,1,0,0

In [18]:
y = final.price

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=10)

In [20]:
reg=LinearRegression()

In [21]:
reg.fit(X_train,y_train)

LinearRegression()

In [22]:
reg.predict(X_test)

array([121.83723992,  93.58350693, 117.70621934, 183.17767403,
        39.60740835, 168.48914197,  27.59431332, 131.37600202,
       208.49392557, 200.04138602, 169.5980508 , 197.58967598,
        82.81717284, 204.15669487, 120.93185753,  52.57179168,
       176.67482769,  91.23833589, 279.28252159, 224.18480611,
        97.99638712, 114.66070108, 123.55703812, 224.15699992,
        50.97603999, 199.72680284, 128.38447808,  25.74555665,
        37.43468625,  81.72025098, 143.51426833,  85.58805045,
        47.23118596,  54.24713678,  99.33742563, 136.82708732,
        79.34773109,  85.64569912, 130.88362713,  33.02672789,
        94.87182374, 227.14421417, 141.72203068,  77.79819339,
        99.30616585,  39.32467198,  77.65038238, 215.2520538 ,
       114.90390746, 144.05771024, 143.070231  , 116.56110515,
       196.25079514, 191.96456313,  44.81685173, 219.20063197,
       107.57541303,  33.68722751,  25.00054531, 100.57696669,
       239.90168465, 150.60954931, 233.44828136,  71.40908291,
        99.39780861, 175.27284174, 209.6126275 , 137.42767645,
        47.78115176,  47.6516415 , 144.63408216,  95.27701098,
        88.34819338, 129.58925821, 269.32997882, 165.41613308,
        24.48897036,  95.58591481, 169.78238477,  75.20778735,
       247.0785847 , 273.94664113, 148.62603787, 217.99273083,
        92.81165951, 106.40684177, 141.64843496,  73.40262791,
       223.96630356,  89.83258931,  75.53081797, 224.2325642 ,
       123.76277186,  99.4159527 ,  25.90304547, 150.97717981,
       164.40554349, 102.06977335, 120.23308955, 171.2667588 ,
       157.34767943, 140.69758154,  81.09128232, 172.48313793,
        54.79851993,  45.88947194,  58.07000249, 207.70667365,
       129.20773609,  76.15685671,  24.58737566, 117.91310169,
       143.46548301,  96.75405119, 216.7352805 ,  93.81947992,
        38.44920721, 112.88046461, 243.61688003,  58.54758334,
       234.43636971,  29.89007865,  31.92829194, 140.28992959,
       195.96438701,  32.2597742 ,  74.07084385,  49.14772306,
        51.4036553 , 135.59029965, 215.29971299, 133.50606262,
       125.134569  ,  94.10278227, 165.47042725, 140.98813303,
       126.51200436, 218.33089935,  42.71118772,  40.92219624,
       262.39574259,  54.09898295, 222.28296514, 166.94719486,
       145.67761172, 127.2968414 , 239.30513121,  79.87087299,
       141.80823293,  50.39804234, 168.43956221, 176.94619638,
       158.6042027 , 120.23574336, 216.2745981 , 164.40709907,
        93.84202077, 218.25733699, 141.69841197,  48.98993532,
       219.86688584,  30.0321831 ,  70.43197887, 179.79007512,
        51.41076621,  89.61184593, 169.64837204,  64.92091608,
       126.02931546, 108.43345387, 147.60517052,  82.69732424,
       114.4477264 ,  28.48198205, 115.09715873, 112.15368385,
       178.33765895,  75.83401959, 107.4553226 , 123.73695612,
       200.5287349 ,  44.76748897, 280.07717363,  39.25827033,
       258.80388973,  73.15667771, 144.10159492,  68.38574881,
        32.5645314 ,  95.20341525, 130.95064586, 219.64125401,
        40.27602154,  87.07622273, 111.09756546,  72.42324368,
        28.95735544,  53.37494002,  97.56715138, 167.99119626,
       213.38379341, 158.79526377, 151.44924295, 190.31781867,
        76.37134548, 150.42497606,  66.1104235 ,  80.29901939,
       111.55911874, 209.68563003, 114.97138896,  70.56024349,
       113.26252929, 122.72930066, 174.65967217, 132.14237905,
       278.36663556, 212.46272823, 147.37990128,  36.64146625,
        55.05741954, 132.33887648, 210.2795179 ,  33.63270691,
        80.40823495,  32.47793253, 133.89455562, 135.1576437 ,
       161.8775682 , 224.45166198, 168.08718667, 216.88333685,
        76.91802136, 132.484975  , 122.63733995, 146.61914918,
       170.17280229, 127.75085417, 121.94322896, 272.40148398,
        85.92754069,  31.92829194, 120.28316546, 192.43724335,
       197.45406118, 100.14487521,  40.44344559, 101.26871392,
       174.02946559,  34.96135294,  64.37363481, 128.38316784,
       120.38784426, 105.45168007,  74.54654175,  30.38515714,
        96.92050927,  87.74928062,  94.89336882, 143.98538142,
        55.03057656, 232.82693011, 113.34811022,  99.06252809,
       263.35713701, 211.08753194, 165.95510309,  52.24578487,
       173.702856  ,  58.56467484,  84.36276488, 147.66827147,
        56.44137677, 118.98578316, 117.99606662, 168.45351123,
        65.97590223, 141.41844046,  67.92523073, 241.71885119,
       145.04197406,  51.5503287 ,  85.68417202,  50.11600869,
        33.1600669 , 152.92826027, 160.94153142,  31.58625756,
       100.81797605,  86.56680896,  51.73302105,  53.06540009,
       179.5342956 , 213.23073099,  67.76876711,  73.44611535,
        72.60996774, 127.6272746 ,  33.95843316, 131.72754402,
       125.87675601,  26.04631972, 119.61266933,  93.03013332,
        85.33787846, 205.65489768,  71.58964237, 273.25264708,
        57.44311633, 208.17649622,  46.57265988,  69.67970475,
        59.38265461,  66.2866618 , 247.85921587, 134.05933733,
        93.46062628, 123.71501378,  43.97426897, 250.8514734 ,
       200.96503689, 129.3569731 ,  55.22430208,  26.89175069,
       225.85468461,  51.68526296, 160.5387161 ,  34.85472243,
        87.53795357, 264.82097353,  87.54283315,  99.95340799,
        52.40839676, 146.39892384, 132.81705583, 219.59455189,
       100.74606817,  87.21091665, 144.41520418,  67.79400823,
        78.36455662, 106.53099865, 158.44776985,  43.35785856,
        77.81830258, 126.91090333,  89.79076191, 120.01451869,
       221.74715333, 137.13335924,  76.91967583, 243.61482831,
       206.1603155 ,  68.76582303, 162.83999957,  83.69438017,
       215.84747894, 213.33785701,  95.71572914,  78.65379831,
       194.95759383,  92.29908938, 255.36370294,  45.84010917,
       115.32221927,  45.81101853, 179.13145843,  99.47138244,
       153.84811763, 152.42474231,  89.09633298, 248.65679853,
       110.93554173, 241.1352813 , 112.42940436, 103.89151329,
       168.28442124,  63.86108658, 107.30699473, 149.6043336 ,
       145.05814201,  85.77968819, 193.72833737, 112.5900732 ,
       274.52017303,  78.67756233, 142.25848395, 133.41475584,
       158.41376355,  72.11653688, 168.00973945,  67.89234873,
       143.0850509 ,  96.37425523, 257.47901918,  49.1941709 ,
       234.18841666,  53.77365781, 271.82990104,  51.75883679,
       174.01134685, 210.78851068, 149.64055883, 134.43696415,
        47.1861124 , 177.11528638, 130.52533795,  45.86322131,
       148.00190787,  49.89627148, 120.45532576,  61.04806652,
        51.09571743, 161.9007452 , 167.2874534 , 111.24406131,
       281.46709894,  95.6097401 ,  90.70203892, 145.32582938,
       201.80985099,  59.3155861 , 124.93637334, 107.46892495,
       110.60126387,  48.28454835,  28.99028209,  97.637522  ,
        37.50826007,  35.51250761, 234.07134392, 114.99991978,
        99.73880074, 136.43835901, 178.49639744, 280.55862788,
       148.68091834, 180.32541055, 195.48060394,  54.62920146,
       154.15885614, 146.05587815, 180.33702041,  44.93270556,
        55.94448549,  45.29773135, 127.99393098, 119.2015638 ,
        32.54914704, 205.43456198,  77.04702493, 104.6364039 ,
        67.94246613, 130.83481308, 244.93334428, 138.33562262,
        53.74110827, 130.25841396,  27.35933503,  89.32917082,
        36.3571654 ,  80.52347453,  80.8550966 , 176.0710676 ,
       160.48013   , 213.43724658,  56.91959907, 169.18886014,
       256.7125305 ,  53.53924793,  52.40610083,  53.52916083,
        92.84727934, 141.38992112, 163.69139115,  95.65788396,
       146.48404644, 132.7473554 ,  65.41986798, 148.65584838,
        81.81647199, 162.19050375,  42.47020026,  49.37539915,
       130.3472665 , 111.89682449, 237.25304764, 144.02940649,
       254.22525571, 170.52340198,  23.13307655, 194.09168482,
        28.49206915,  59.97651375, 113.31472524, 107.18731728,
       100.67304732,  71.37973799,  47.57806767, 143.47215948,
        89.68608311, 119.94276654, 134.27830554,  27.55036737,
       145.35006765, 131.2658705 ,  86.75023424, 261.19793609,
        52.27559538, 102.48508263,  34.78566346, 113.57547702,
       172.71757028, 252.60769453,  39.7047462 ,  91.60066568,
       163.75925842, 106.64185769, 180.91001853, 193.32879695,
       112.73555491,  44.36969564, 193.28101696,  54.34265295,
       131.50177863, 266.80099735, 109.9781611 ,  54.77475591,
        95.03498861, 197.17358311, 126.60513439,  59.14450565,
        68.39810463,  96.32223797, 189.75583599,  62.94132714,
        97.98230147, 224.85403355, 281.49746243, 147.09999809,
       104.92290262, 128.06363141, 112.94854106, 155.41777301,
       164.68757714, 157.29114443, 220.64030039, 225.26576836,
        31.70044117, 136.47248602,  48.32247361, 220.11661593,
       267.49710265, 139.5751358 , 101.82358035,  85.17084019,
       207.12930598,  34.2804452 ,  87.48737806, 256.90979556,
       203.47545327, 111.78438798,  35.78896902, 103.8058231 ,
       218.1371853 , 157.29767164,  76.31746429, 191.0626376 ,
       237.81614816,  32.92309816, 150.64939339, 133.98743987,
       150.09690219, 135.78623544,  31.29256075,  96.12831651,
        32.14362593,  51.64244572, 164.48742858,  43.09557022,
       257.14083918,  50.62691344,  34.24649575,  93.05883819,
        97.934403  ,  84.72089676,  43.39023229,  47.73070915,
       163.8306248 ,  54.34105975, 110.89653662, 117.4135785 ,
        76.72375151,  31.51268373, 202.57398035,  47.62333774,
        35.76094582,  50.68234318, 204.99439806,  48.5161666 ,
        99.95833052,  98.37805455, 107.6160726 , 136.32063142,
       169.01768411, 143.3106759 , 150.81681744,  94.62644483,
       111.55524534,  32.13315306,  50.54400977, 183.76635198,
        49.45490366,  55.34396805, 128.69996995,  72.3854821 ,
        98.98003761, 175.35961881,  45.00589361, 174.8622394 ,
       142.11520969,  96.03724503,  54.03594615, 212.92708746,
       129.58452253,  61.65185885,  45.0775845 ,  53.08970175,
        84.28877807, 245.7782884 , 139.05411402,  59.38147439,
        75.86410598, 106.79173142, 161.87475077,  50.79600344,
       241.34981155, 188.91153333, 188.86310505, 110.19789831,
       166.45681648, 149.82546807, 159.98598395,  94.38815056,
       212.97541685, 136.80904028, 260.94341702, 113.16045514,
        38.08097132,  41.84934516, 113.98277396, 137.78433837,
       179.77425588, 204.60239814, 106.54246812, 213.6008087 ,
       175.06003426, 202.83916114, 128.34142694, 136.2539903 ,
        97.91185526, 213.85041623,  34.88317009, 142.69573557,
       131.57252819,  73.40751989, 237.88321667,  87.53900954,
        69.69904239, 146.65965661,  85.65775088, 138.78526769,
       190.19752547,  45.87601202,  67.59092413, 184.1563985 ,
       167.55969712, 159.89085355,  25.85490161,  51.9141628 ,
       144.15810599, 112.94969939, 270.38065668,  54.31640232,
        85.18535367,  44.83391449,  50.46078816,  95.17991733,
       210.72856109, 185.80496189, 195.10074672, 103.07518115,
       134.80139477,  96.30019673, 197.91785947, 118.56825495,
       206.17569986, 106.894854  ,  70.79516051,  44.30857556,
        29.68602127, 114.94237352, 125.8943812 ,  87.93811593,
       180.39898438,  88.58969888,  53.84152508, 104.92295241,
        71.41381858, 196.82776555, 124.86223505, 101.89610511,
       279.75104539, 125.76917589, 169.1081754 ,  80.42084745,
       100.27842256, 127.30582286,  46.48639424,  65.53261954,
       125.35212193, 219.23830296,  93.67128314,  91.43118991,
        96.119565  , 107.33231432, 178.83835194, 230.45489778,
        96.58230054,  49.46869638, 117.37652176,  87.66137151,
       157.96867492, 214.2088841 ,  98.17097449, 106.5369506 ,
       103.64579015, 212.62959929,  91.84214063,  84.34412131,
        76.51697905,  55.34291208,  49.30229957,  43.10085945,
       192.34557184,  67.38282903, 109.70497459, 132.38386265,
       100.03811805, 213.93832534, 174.05307388,  64.72543905,
       142.91151621,  99.95794475,  58.80346526,  55.32203718,
       124.26554122, 122.55129336, 225.7094199 , 155.73590017,
       273.27077729, 136.18882663, 155.63710911, 149.43532061,
       167.57990521, 129.84067705,  90.58353134,  88.02758618,
        29.29547417, 104.69868695, 101.62494096,  48.86978362,
        82.93450999,  38.9988478 ,  90.64328505,  84.35895275,
       160.12743652,  50.54805038,  32.58202904, 152.66131381,
       209.33204174,  39.44930267, 196.8655884 , 163.98114287,
        42.66392578, 248.99160127,  29.29348371, 102.27921886,
       226.0475999 , 180.76717915,  41.41952239,  65.13556713,
        27.15248345,  27.667391  ,  48.94332872, 119.82348635,
       184.94472317,  50.90363596,  96.83172689,  46.59460222,
        92.79234908,  79.1774713 , 151.94001316, 102.5647183 ,
        91.32198534,  28.33600419, 210.22080179, 265.40167761,
        45.88459236, 148.02220258,  64.7793182 , 189.68613556,
        75.31289004, 102.23977204, 269.20320638,  30.39009798,
       146.74034135,  35.08032553,  35.83672711, 178.42605556,
       134.10332091,  35.47332987, 179.76614232,  33.8151589 ,
       168.89901285,  26.33286823, 161.60202238,  62.39361099,
        70.3867088 ,  60.7659627 , 130.75100444, 107.91150367,
        70.07928539, 284.78617081,  26.18689037, 169.85747332,
        32.20221203, 162.75633864,  41.29123587,  63.41509586,
        43.30565578, 163.60132585, 169.54302988, 108.31339066,
       238.10275793, 117.98667551, 143.30192088,  77.70796646,
        62.56643464, 138.14120155, 112.02021369,  99.26738922,
       146.88219977, 100.0034839 , 101.32980527, 181.12735128,
       132.19664244,  76.29774088, 110.09091267, 131.52981331,
       209.27997537, 101.64855967, 102.01131392, 125.0626087 ,
       128.25853715,  88.25489614,  31.72914604, 158.98892802,
       167.99787273, 202.3774303 ,  38.62863837, 105.47140348,
        77.14700769, 118.00861786,  93.78110409, 260.43766112,
       174.30803225, 186.36487158, 131.0703014 , 240.60645474,
       122.85371378,  27.42860058, 124.60372121, 145.19623262,
       196.01685204, 102.05476372, 103.86734518, 120.2786287 ,
       163.13900182, 262.29416459,  79.10506727, 113.29056397,
       128.54969468, 128.4172197 ,  38.69731156,  99.9599352 ,
        49.06533082,  41.1957197 ,  71.66523743, 216.20102427,
       114.15730449,  51.88305783,  52.28417572, 214.019162  ,
       184.47144727, 147.64506043, 274.5614258 ,  59.43105416,
        91.1824441 , 271.81990454, 101.20773774,  55.28435472,
        99.84930464,  80.92219232, 207.67658726, 277.76185894,
        43.81393195, 193.13774271,  99.11569797,  38.07865349,
       112.18828511,  46.06795304, 140.37266605, 207.96083984,
       102.40172063, 225.86787398, 107.25923664,  51.5222653 ,
        67.75294787, 245.52670727, 201.21156264, 165.93925308,
        78.30158999,  48.10091859,  24.2315125 , 150.72189977,
       209.77118047, 125.45137111, 126.11004906, 122.2487551 ,
        57.18353505, 159.12673567, 111.79033992, 205.56362167,
       181.82281027, 201.32903263, 109.46116216, 112.46601937,
       140.7833708 , 210.65886066, 224.75038481, 156.20101974,
       159.59227864, 250.03840573,  47.80979183,  22.13015677,
       171.59497306, 151.77924127, 179.03442818, 178.21372233,
       109.62635003, 124.66899525,  26.69789402,  53.27615584,
        99.7296272 , 102.00700564,  85.14906505, 188.98931654,
        55.43909844, 136.93468935,  52.6706851 , 112.5187183 ,
       176.49378982, 117.25387961, 118.06252954,  50.23545765,
       225.12098002,  25.39637398, 134.00780474, 188.57761251,
        41.07438779,  53.79376699, 207.00345921, 241.21801776,
        41.80648771, 119.92998683, 129.72321854,  62.97326599,
        40.44344559,  48.58707978,  39.09200466,  53.26842806,
       177.24025306,  55.18058461,  26.90375779,  89.50552365,
       103.87671241, 104.24825837, 208.58110175, 122.54741996])

In [23]:
X_train

,total_sqft,bath,bhk,Adyar,Anna Nagar,Kodambakkam,Medavakkam,Nungambakkam,Sholinganallur,T. Nagar,Tambaram,Thiruvanmiyur
2733,4428,3,4,False,False,True,False,False,False,False,False,False
447,3209,1,3,False,False,False,False,False,True,False,False,False
970,2688,1,3,False,False,False,True,False,False,False,False,False
125,3473,2,4,False,False,False,False,True,False,False,False,False
798,2877,4,5,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1180,2378,4,3,False,False,True,False,False,False,False,False,False
3441,2092,1,2,False,False,False,False,False,False,False,True,False
1344,4469,1,4,False,False,False,False,False,False,False,True,False
4623,1644,1,3,False,False,False,False,False,False,False,False,False
1289,5136,1,5,False,True,False,False,False,False,False,False,False

In [24]:
y_train

2733    190.40
447      96.99
970     124.49
125     114.02
798     190.69
         ...
1180    162.91
3441    101.69
1344    247.22
4623     87.58
1289    357.92
Name: price, Length: 4000, dtype: float64

In [25]:
reg.score(X_train,y_train)

0.7497372653296503

In [26]:
reg.predict([[4428,3,4,0,0,1,0,0,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([211.99880895])

In [27]:
reg.predict([[3209,1,3,0,0,0,0,0,1,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([152.9177874])

In [28]:
reg.predict([[2688,1,3,0,0,0,1,0,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([128.75418694])

In [29]:
reg.predict([[3473,2,4,0,0,0,0,1,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([164.47457373])

In [30]:
from sklearn.ensemble import RandomForestRegressor

In [31]:
rf_model = RandomForestRegressor()
rf_model.fit(X_train, y_train)

RandomForestRegressor()

In [32]:
rf_model.predict(X_test)

array([119.0479    , 107.245     ,  97.1882    , 129.4431    ,
        32.7072    , 151.9269    ,  32.07214667, 128.0218    ,
       194.9141    , 186.4062    , 147.1088    , 151.4976    ,
        88.131     , 195.0755    , 157.971     ,  42.4099    ,
       172.1541    ,  96.0661    , 231.2479    , 275.1101    ,
        91.9605    , 120.5487    , 128.4149    , 245.8088    ,
        56.1377    , 158.3176    , 158.4615    ,  26.3794    ,
        40.06245833,  68.8637    , 164.4407    ,  81.6384    ,
        46.7518    ,  56.1086    ,  92.83911333, 126.1038    ,
        75.8947    ,  95.0639    , 104.8751    ,  35.35653333,
       125.8396    , 283.5857    , 143.34      ,  65.1926    ,
        88.0677    ,  46.4295    ,  97.3028    , 225.2311    ,
       109.2086    , 157.0759    , 128.1421    , 103.2721    ,
       184.9951    , 195.8563    ,  51.6075    , 187.5117    ,
       112.0901    ,  39.9845    ,  25.67286   , 113.2629    ,
       260.8077    , 157.3488    , 217.1974    ,  79.7768    ,
        87.8313    , 199.3523    , 209.5459    , 155.1086    ,
        45.09861667,  57.73803   , 149.0747    , 115.1068    ,
       101.682     , 113.9193    , 267.4997    , 183.9663    ,
        27.4062    ,  96.5575    , 187.1205    ,  86.7947    ,
       263.1196    , 288.8206    , 122.7755    , 268.3317    ,
        82.2789    , 111.3712    , 142.2408    ,  60.5485    ,
       210.2121    ,  89.9749    ,  75.62086667, 274.8891    ,
       122.627     , 112.8218    ,  25.9408    , 152.1786    ,
       140.0831    , 110.9861    , 101.3735    , 155.6945    ,
       131.2728    , 114.6621    ,  82.939     , 204.2106    ,
        45.4146    ,  33.1381    ,  49.9736    , 186.7066    ,
       113.5852    ,  91.6672    ,  30.1116    , 133.0339    ,
       155.0319    ,  93.9237    , 162.3752    , 114.0449    ,
        39.2813    ,  88.823     , 234.7249    ,  49.1947    ,
       257.3486    ,  34.5355    ,  22.2904    , 140.0621    ,
       158.5089    ,  31.0933    ,  82.2007    ,  50.7074    ,
        47.14026667, 156.2383    , 224.4085    , 131.4796    ,
       132.3023    ,  90.1307    , 142.2781    , 154.2443    ,
       108.6688    , 203.4145    ,  41.7275    ,  43.6792    ,
       256.6644    ,  56.90836429, 199.6314    , 185.6552    ,
       137.6947    , 113.4934    , 231.545     ,  65.736     ,
       144.5674    ,  50.9318    , 141.2158    , 200.2336    ,
       183.5263    , 116.3523    , 222.1842    , 155.7069    ,
       110.        , 236.1544    , 153.6408    ,  49.27569167,
       185.1579    ,  32.03525   ,  82.5652    , 217.2161    ,
        60.77554167,  93.8355    , 148.1885    ,  62.45325   ,
       120.2934    , 122.0614    , 128.7131    ,  73.2697    ,
       105.3644    ,  21.045     , 114.1749    , 112.1222    ,
       165.0741    ,  78.4008    , 105.9803    , 153.244     ,
       207.3325    ,  42.4874    , 239.4577    ,  35.7855    ,
       244.5566    ,  76.6828    , 127.4084    ,  46.4457    ,
        30.2537    ,  90.1471    , 108.3429    , 197.8684    ,
        31.9488    ,  73.2953    , 101.0892    ,  72.9261    ,
        33.4605    ,  48.725775  , 107.0913    , 141.0254    ,
       228.5911    , 198.3543    , 167.8351    , 218.4564    ,
        81.365     , 150.7005    ,  58.58235333,  67.4703    ,
       121.8013    , 222.7265    , 117.7807    ,  55.636     ,
       112.9012    , 110.6299    , 148.795     , 107.7196    ,
       269.2505    , 205.434     , 155.7598    ,  39.1256    ,
        51.7715    , 115.6474    , 233.779     ,  45.0795    ,
        73.2339    ,  31.6855    , 120.7395    , 103.6243    ,
       174.9135    , 189.1141    , 196.5899    , 214.391     ,
        75.14741667, 151.1424    , 134.8481    , 167.2566    ,
       178.7643    , 120.6849    , 126.1087    , 282.2731    ,
        73.6705    ,  22.2904    , 106.2376    , 197.3449    ,
       204.0434    , 114.55511667,  41.01171667, 113.921     ,
       199.0809    ,  24.5703    ,  63.38845   , 121.4408    ,
        89.4616    ,  98.7727    ,  78.0539    ,  32.1032    ,
        88.9737    ,  73.4454    , 103.6465    , 176.8745    ,
        49.4445    , 229.3604    , 134.8502    , 119.4589    ,
       217.2969    , 237.3706    , 165.4883    ,  52.8949    ,
       165.9147    ,  50.2096    ,  83.9086    , 120.9136    ,
        54.905     , 155.881     , 117.506     , 196.3741    ,
        52.8555    , 144.1857    ,  62.8197    , 245.9336    ,
       138.5966    ,  60.0335    ,  78.0598    ,  48.6608    ,
        32.5843    , 134.7068    , 169.1882    ,  23.0352    ,
       104.0403    ,  83.5891    ,  60.1964    ,  60.2093    ,
       190.7882    , 220.7449    ,  73.824     ,  79.7323    ,
        75.1256    , 122.2778    ,  30.3677    , 161.0122    ,
       142.1136    ,  25.8357    , 136.4112    , 102.4475    ,
        79.8231    , 187.3522    ,  72.4412    , 270.5423    ,
        55.0369    , 267.633     ,  54.8276    ,  83.5189    ,
        54.2941    ,  80.679     , 302.2123    , 110.0853    ,
       103.746     , 127.8789    ,  31.0661    , 233.8305    ,
       196.593     , 138.5995    ,  55.01554167,  26.7898    ,
       258.3349    ,  65.8815    , 166.76065   ,  29.1213    ,
        75.5457    , 202.1634    ,  74.7995    , 112.81098   ,
        56.9341    , 145.0812    , 142.3221    , 225.8213    ,
        95.0438    ,  97.4673    , 167.7576    ,  67.9236    ,
        84.09993333, 115.8633    , 171.528     ,  46.4797    ,
        66.5899    , 123.2535    ,  97.5258    , 127.3634    ,
       178.4643    , 130.5403    ,  69.6668    , 234.6397    ,
       268.9986    ,  82.1006    , 157.1922    ,  91.7142    ,
       230.9724    , 164.4337    ,  93.0056    ,  81.3421    ,
       178.0825    ,  97.3621    , 271.0514    ,  55.86475   ,
       104.4104    ,  44.0088    , 205.6333    ,  76.8346    ,
       126.0268    , 128.282     ,  94.4613    , 281.9898    ,
        96.5762    , 252.5028    , 130.2498    ,  80.9091    ,
       187.3812    ,  82.4168    ,  92.6763    , 133.4092    ,
       144.8493    ,  77.7606    , 190.3834    , 127.9177    ,
       283.5426    ,  61.6058    , 154.7907    , 145.8834    ,
       168.755     ,  66.4404    , 156.6231    ,  60.2758    ,
       147.1464    , 102.0484    , 245.389     ,  65.6368    ,
       246.8109    ,  55.8459    , 301.8135    ,  53.207     ,
       160.9223    , 252.2967    , 158.4558    , 122.6114    ,
        50.25096667, 178.9792    , 138.6744    ,  36.1452    ,
       171.9468    ,  44.4325    , 130.2829    ,  75.2238    ,
        57.207875  , 184.001     , 180.8078    , 107.6374    ,
       231.4888    ,  70.4947    ,  95.1709    , 175.383     ,
       184.6857    ,  62.08783   , 106.9857    , 104.8484    ,
       109.5609    ,  52.5528    ,  18.9015    ,  89.12462   ,
        35.951     ,  35.2037    , 238.268     ,  97.9818    ,
       102.35014   , 130.7028    , 167.3686    , 268.3814    ,
       183.0253    , 203.6823    , 217.8998    ,  57.9725    ,
       175.301     , 146.7301    , 205.5549    ,  46.460325  ,
        48.002975  ,  57.8911    , 134.8146    , 115.324     ,
        31.81237333, 210.1655    ,  72.84055   , 125.3227    ,
        72.5185    , 181.24      , 264.325     , 145.7283    ,
        46.5204    , 115.2231    ,  27.88456667,  99.6532    ,
        40.8968    ,  80.6149    ,  67.202     , 182.5523    ,
       183.6759    , 211.4671    ,  52.6857    , 143.7406    ,
       216.7219    ,  53.4976    ,  64.0674    ,  49.7614    ,
        76.4393    , 146.6217    , 146.0527    ,  94.6996    ,
       156.7532    , 138.0923    ,  65.8218    , 143.2312    ,
        72.6826    , 173.1395    ,  45.3895    ,  44.6398    ,
       140.19      , 107.1827    , 234.4785    , 147.1997    ,
       252.9386    , 198.7592    ,  24.6346    , 211.5014    ,
        29.2431    ,  53.2401    , 110.8479    , 106.3569    ,
       108.0068    ,  68.1602    ,  52.256     , 132.6424    ,
        97.92      ,  91.7389    , 113.5119    ,  23.36226667,
       168.3859    , 126.7545    ,  84.3631    , 240.8598    ,
        57.1425    ,  86.1926    ,  30.4514    , 115.4193    ,
       153.5961    , 253.4542    ,  33.6282    ,  86.6416    ,
       171.3039    , 137.4254    , 183.2522    , 173.4974    ,
       129.378     ,  45.8455    , 202.5492    ,  60.8952    ,
       131.7359    , 218.336     ,  92.5753    ,  58.4666    ,
        94.8394    , 199.1063    , 125.3232    ,  70.19975   ,
        67.184     ,  94.5351    , 156.9804    ,  54.7441    ,
       107.9764    , 250.7925    , 282.3124    , 122.8869    ,
       100.304     , 125.1498    ,  98.3997    , 130.2807    ,
       189.1406    , 153.4562    , 224.0618    , 196.1235    ,
        37.301     , 152.3444    ,  49.7181    , 238.1385    ,
       227.2653    , 149.8225    ,  96.5784    ,  81.3348    ,
       197.5543    ,  37.1429    , 100.2098    , 204.7191    ,
       230.7893    , 123.0517    ,  35.1416    ,  98.2028    ,
       212.9454    , 154.3027    ,  84.8898    , 166.9452    ,
       262.5173    ,  35.7701    , 166.2821    , 112.3331    ,
       140.4042    , 162.0362    ,  36.4357    , 119.0092    ,
        34.6441    ,  59.70116667, 198.1948    ,  57.9496    ,
       238.1229    ,  52.9424    ,  34.4213    , 115.8051    ,
        99.0023    ,  72.0661    ,  53.4883    ,  47.1657    ,
       203.2193    ,  56.8157    , 103.1177    , 135.8394    ,
        63.02      ,  33.5795    , 177.8675    ,  48.5281    ,
        40.6704    ,  56.4752    , 242.6837    ,  52.1565    ,
       101.8424    ,  94.01446667,  99.7525    , 149.1673    ,
       154.836     , 141.6132    , 195.2397    ,  89.0833    ,
       113.6707    ,  31.1112    ,  45.124575  , 168.5481    ,
        63.3278    ,  47.0322    , 114.6035    ,  63.2917    ,
       102.90965   , 157.5417    ,  38.5705    , 178.8929    ,
       153.7862    ,  97.7471    ,  47.5826    , 167.9017    ,
       157.973     ,  72.47398   ,  45.5267    ,  56.146     ,
        86.2471    , 253.0036    , 138.7766    ,  56.2481    ,
        78.5586    ,  91.68886667, 161.0714    ,  51.0916    ,
       279.663     , 183.8966    , 214.897     , 121.4856    ,
       141.5628    , 180.9144    , 160.5947    ,  93.2047    ,
       239.0526    , 111.0777    , 201.7857    ,  88.2527    ,
        44.13489167,  47.2359    , 106.8974    , 140.1097    ,
       188.2968    , 225.0641    , 130.878     , 212.9687    ,
       209.9245    , 226.8225    , 135.3966    , 139.1554    ,
       107.4299    , 229.6603    ,  36.7473    , 133.6519    ,
       124.2925    ,  74.2413    , 234.8455    ,  90.8092    ,
        65.48732667, 132.2526    ,  98.3557    , 113.5623    ,
       152.3057    ,  52.72470833,  64.663     , 154.8883    ,
       147.5268    , 164.6069    ,  31.5281    ,  55.8898    ,
       138.6582    ,  91.0712    , 292.0454    ,  40.8789    ,
        82.2343    ,  47.171825  ,  48.986     , 106.1052    ,
       213.9829    , 134.6461    , 205.8412    ,  88.0104    ,
       114.2228    ,  82.2456    , 163.0809    , 146.358     ,
       215.2973    ,  91.05228   ,  71.7769    ,  38.5916    ,
        25.88666667,  92.7267    , 146.4629    ,  97.8808    ,
       161.992     ,  80.3753    ,  55.5565    , 127.3866    ,
        78.2118    , 160.7524    , 114.4434    , 102.927     ,
       246.2141    , 111.952     , 157.3162    ,  77.637     ,
       105.36203333,  99.9774    ,  49.7233    ,  71.51936   ,
       103.6545    , 224.3334    ,  76.5816    ,  98.8579    ,
        98.4339    ,  99.6747    , 153.8467    , 262.1285    ,
       104.1744    ,  42.6642    , 135.0274    ,  80.6041    ,
       125.257     , 224.4579    ,  92.7112    , 101.8427    ,
        98.84179167, 211.1997    ,  89.5188    ,  90.1859    ,
        81.0843    ,  66.4569    ,  42.3783    ,  46.8092    ,
       189.0507    ,  57.12015   , 114.1519    , 161.748     ,
       109.4579    , 230.7547    , 157.8949    ,  69.9117    ,
       156.0368    , 100.7931    ,  47.8363    ,  58.5604    ,
        97.1816    , 107.6278    , 212.2199    , 175.0022    ,
       320.7671    , 147.0918    , 163.3915    , 156.2097    ,
       122.4288    , 150.7763    ,  79.5112    , 100.6       ,
        22.8621    , 114.6853    , 115.0358    ,  54.765225  ,
        93.7962    ,  34.0118    ,  79.3011    ,  75.4766    ,
       143.1328    ,  47.1348    ,  36.1329    , 116.7816    ,
       265.3769    ,  43.3187    , 200.8505    , 179.2847    ,
        38.9985    , 272.5623    ,  29.9157    , 114.05846667,
       209.6502    , 211.8454    ,  41.909     ,  54.218725  ,
        26.9601    ,  27.1669    ,  53.4402    , 124.4261    ,
       158.0214    ,  49.7731    , 101.2006    ,  54.2632    ,
        96.4592    ,  81.1176    , 169.1753    ,  90.1445    ,
        79.2209    ,  27.3398    , 249.456     , 268.3964    ,
        61.2517    , 167.462     ,  51.75375   , 170.0726    ,
        82.2323    , 104.96646667, 257.0721    ,  30.34895   ,
       169.0981    ,  27.4536    ,  35.1632    , 173.9992    ,
       153.7812    ,  39.3221    , 190.12      ,  38.0849    ,
       164.3332    ,  25.9963    , 179.9749    ,  58.1463    ,
        64.70284   ,  73.51484167, 152.7808    , 117.5401    ,
        83.6739    , 232.3426    ,  29.8598    , 156.5716    ,
        32.2016    , 182.3791    ,  48.1096    ,  74.0319    ,
        44.586     , 196.2434    , 171.054     ,  83.3454    ,
       244.6933    , 138.0789    , 161.7595    ,  62.2367    ,
        59.816     , 121.7722    , 131.0485    ,  84.0233    ,
       148.3678    , 109.534     , 107.8342    , 168.6258    ,
       113.3629    ,  90.9468    , 118.1772    , 134.8305    ,
       225.5506    , 122.0593    , 108.0161    , 100.7282    ,
       135.8156    ,  86.4328    ,  29.7943    , 160.67706667,
       182.5792    , 186.4006    ,  35.4545    , 106.85088333,
        83.8843    , 132.9872    ,  99.9847    , 262.3649    ,
       168.0003    , 134.5228    , 151.7809    , 211.2276    ,
       148.0492    ,  30.4822    ,  96.1823    , 137.336     ,
       171.0491    ,  98.1236    ,  97.36431667,  94.8494    ,
       155.25239167, 282.2971    ,  94.7518    , 128.8031    ,
       142.758     , 122.4122    ,  36.9854    , 124.4115    ,
        47.70073333,  44.2106    ,  67.631     , 219.1932    ,
       125.781     ,  54.1053    ,  51.3212    , 185.7752    ,
       156.9237    , 146.8083    , 288.9145    ,  68.6849    ,
        90.64      , 256.5841    , 112.0172    ,  55.0976    ,
       105.3024    ,  77.0445    , 205.1652    , 273.03      ,
        46.6232    , 201.4341    ,  96.31046667,  33.5824    ,
       108.8364    ,  42.2791    , 144.9687    , 215.101     ,
        94.9228    , 198.7582    ,  93.3076    ,  53.3769    ,
        69.81416   , 223.4308    , 238.221     , 187.9247    ,
        70.1987    ,  48.8171    ,  27.9903    , 168.3629    ,
       212.4165    , 109.5192    ,  99.992     , 101.4948    ,
        58.6906    , 180.1566    , 106.8162    , 204.4162    ,
       166.7698    , 201.2107    ,  95.9711    ,  97.7861    ,
       151.6458    , 217.9955    , 205.8722    , 149.1861    ,
       157.2919    , 265.0418    ,  45.3114    ,  26.0733    ,
       180.8478    , 143.3497    , 201.0186    , 171.4655    ,
        95.1226    , 118.9465    ,  31.4097    ,  63.9704    ,
       123.9587    , 101.6691    ,  83.9991    , 213.4447    ,
        42.25633333, 134.2496    ,  74.2446    , 104.1298    ,
       151.0061    , 131.5793    , 107.3635    ,  52.1244    ,
       256.3165    ,  33.8104    , 155.9889    , 178.1805    ,
        33.1186    ,  58.7444    , 207.6428    , 243.7327    ,
        40.4705    , 129.4241    , 141.5641    ,  68.0213    ,
        41.01171667,  49.0167    ,  41.4344    ,  43.89985   ,
       189.6577    ,  56.6103    ,  30.1027    ,  89.7356    ,
       114.3344    ,  86.3151    , 210.0885    , 147.641     ])

In [33]:
rf_model.score(X_train,y_train)

0.9590717572825167

In [34]:
rf_model.predict([[4428,3,4,0,0,1,0,0,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([212.0991])

In [35]:
rf_model.predict([[3209,1,3,0,0,0,0,0,1,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([108.0501])

In [36]:
rf_model.predict([[2688,1,3,0,0,0,1,0,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([128.3548])

In [37]:
rf_model.predict([[3473,2,4,0,0,0,0,1,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([127.4127])

In [38]:
from sklearn.tree import DecisionTreeRegressor

In [52]:
reg_model = DecisionTreeRegressor()
reg_model.fit(X_train, y_train)

DecisionTreeRegressor()

In [54]:
reg_model.predict(X_test)

array([107.29 ,  64.41 ,  68.89 , 115.07 ,  29.87 , 213.65 ,  35.23 ,
        76.3  , 196.82 , 254.83 , 130.9  , 114.56 ,  78.21 , 113.43 ,
       174.93 ,  38.96 , 122.27 , 125.48 , 185.59 , 232.49 , 115.12 ,
        94.92 , 161.32 , 235.06 ,  69.94 , 155.07 , 184.69 ,  26.4  ,
        55.14 ,  45.73 , 180.44 ,  69.73 ,  57.03 ,  49.32 , 121.29 ,
       165.99 ,  51.45 , 115.03 ,  86.19 ,  36.91 , 134.65 , 328.85 ,
       134.88 ,  45.36 ,  71.31 ,  50.46 , 105.66 , 275.25 ,  93.71 ,
       200.93 ,  96.51 ,  82.25 , 153.75 , 193.48 ,  55.72 , 155.55 ,
       143.45 ,  44.09 ,  28.93 ,  88.2  , 335.97 , 192.36 , 161.23 ,
        89.41 , 136.99 , 239.1  , 223.97 , 184.65 ,  43.595,  68.2  ,
       147.46 , 134.65 , 111.65 , 158.09 , 320.89 , 236.68 ,  33.27 ,
       119.43 , 154.03 ,  88.55 , 357.92 , 176.84 , 113.17 , 269.99 ,
        66.6  , 122.11 , 150.24 ,  48.16 , 237.55 ,  72.12 ,  91.91 ,
       232.49 , 173.33 ,  94.57 ,  23.71 , 175.35 , 124.01 , 121.44 ,
        90.2  , 139.33 ,  84.68 , 109.45 ,  81.97 , 143.85 ,  31.54 ,
        23.84 ,  35.1  , 155.77 ,  92.77 , 106.91 ,  32.32 , 169.03 ,
       142.63 ,  61.39 , 128.4  , 131.91 ,  46.35 ,  62.46 , 227.06 ,
        35.1  , 278.4  ,  39.87 ,  18.93 ,  75.74 , 220.75 ,  30.84 ,
        98.95 ,  58.99 ,  39.93 , 152.99 , 236.23 , 138.87 , 164.22 ,
        57.5  , 142.02 , 145.3  , 101.08 , 227.88 ,  40.87 ,  46.22 ,
       262.17 ,  67.25 , 210.24 , 108.26 , 147.46 , 114.24 , 240.86 ,
        88.68 , 109.45 ,  65.13 ,  99.28 , 178.46 , 223.805, 107.07 ,
       162.02 , 150.96 ,  58.64 , 269.99 , 150.24 ,  29.85 , 231.45 ,
        32.6  ,  89.41 , 237.65 ,  55.29 , 116.19 , 111.04 ,  51.1  ,
       106.6  , 157.06 , 136.89 ,  52.73 , 143.55 ,  18.2  , 162.65 ,
       129.19 , 152.36 ,  53.97 ,  90.85 , 144.95 , 125.64 ,  39.41 ,
       150.15 ,  43.59 , 176.91 ,  67.74 , 116.36 ,  37.89 ,  26.95 ,
        63.29 , 125.44 , 129.66 ,  22.83 ,  72.31 ,  65.87 ,  90.16 ,
        32.97 ,  57.88 , 143.12 ,  99.28 , 246.59 , 181.72 , 184.08 ,
       245.07 ,  95.86 , 209.67 ,  86.8  ,  51.45 , 146.47 , 139.78 ,
       118.5  ,  57.64 ,  99.19 ,  99.89 , 126.06 ,  96.16 , 216.97 ,
       182.13 , 148.85 ,  48.21 ,  33.85 ,  72.88 , 190.4  ,  48.54 ,
        73.12 ,  29.33 , 190.98 ,  71.42 , 241.28 , 231.45 , 111.53 ,
       167.17 ,  53.11 , 186.98 , 137.54 , 183.11 , 161.9  ,  99.18 ,
       119.99 , 383.01 ,  62.6  ,  18.93 , 144.02 , 232.05 , 189.41 ,
       144.87 ,  62.07 , 133.49 , 205.27 ,  22.98 ,  53.6  , 109.86 ,
        74.93 ,  99.01 ,  54.51 ,  19.99 ,  74.68 ,  59.75 ,  73.56 ,
       186.85 ,  67.13 , 218.51 , 152.   , 138.31 , 175.28 , 252.16 ,
       224.42 ,  59.53 ,  95.12 ,  39.35 , 104.46 ,  94.47 ,  41.75 ,
       170.5  , 108.36 , 177.29 ,  50.57 , 172.61 ,  94.46 , 217.53 ,
        86.27 ,  62.81 ,  81.95 ,  66.6  ,  31.69 , 114.04 , 151.05 ,
        18.69 ,  88.2  ,  85.23 ,  69.94 ,  75.01 , 249.98 , 253.89 ,
        94.3  ,  54.51 , 102.93 ,  92.77 ,  42.17 , 181.59 , 156.42 ,
        23.71 , 107.07 ,  58.64 ,  63.01 , 123.74 ,  51.28 , 383.01 ,
        48.1  , 231.47 ,  69.43 ,  69.21 ,  48.06 ,  90.85 , 340.94 ,
        72.88 , 108.25 , 173.33 ,  24.45 , 149.56 , 260.15 , 141.84 ,
        47.81 ,  27.06 , 121.92 ,  69.94 , 184.04 ,  21.5  ,  64.52 ,
       185.54 ,  71.39 , 144.06 ,  65.74 , 116.36 , 128.13 , 233.02 ,
        66.09 , 127.11 , 109.61 ,  61.47 ,  72.98 , 143.45 , 156.98 ,
        44.81 ,  51.45 , 144.32 ,  91.53 , 156.17 , 130.94 , 165.99 ,
        88.68 , 169.12 , 286.38 , 101.17 , 234.63 ,  97.06 , 277.84 ,
       184.57 ,  81.77 ,  97.58 , 191.14 ,  93.83 , 376.39 ,  34.21 ,
       152.62 ,  58.61 , 177.27 ,  65.54 , 113.   , 116.13 ,  94.18 ,
       154.65 ,  81.61 , 213.19 , 126.28 ,  77.9  , 177.29 ,  94.79 ,
       113.01 , 100.03 , 171.68 ,  81.95 , 282.11 , 121.8  , 297.09 ,
        64.2  , 100.55 , 190.98 , 150.99 ,  48.16 , 180.2  ,  36.75 ,
       189.05 , 108.86 , 139.36 ,  65.41 , 188.69 ,  70.55 , 208.46 ,
        73.53 , 132.89 , 283.06 , 106.63 , 153.62 ,  67.44 , 219.59 ,
       176.36 ,  28.75 , 156.62 ,  55.12 , 177.25 ,  68.26 ,  43.47 ,
       199.09 , 238.79 ,  65.55 , 185.59 ,  58.26 , 107.98 , 192.73 ,
       173.06 ,  58.68 ,  99.18 ,  87.8  , 127.22 ,  41.83 ,  17.46 ,
        64.45 ,  30.74 ,  42.34 , 340.89 ,  71.37 , 138.54 ,  74.49 ,
       178.46 , 313.63 , 184.36 , 185.3  , 251.76 ,  62.61 , 191.13 ,
       198.97 , 183.09 ,  36.44 ,  41.25 ,  61.53 , 101.08 ,  91.76 ,
        40.4  , 133.51 ,  54.43 , 139.47 ,  69.08 , 186.19 , 286.74 ,
       152.99 ,  28.7  ,  77.22 ,  18.51 ,  73.03 ,  48.51 ,  73.18 ,
        50.   , 235.53 , 171.99 , 212.77 ,  55.74 , 213.65 , 186.55 ,
        48.39 ,  62.47 ,  41.75 ,  51.52 , 151.69 ,  95.5  ,  95.13 ,
       184.36 , 186.19 ,  89.64 , 136.89 ,  46.91 , 130.73 ,  47.88 ,
        31.15 , 178.16 , 148.22 , 188.69 , 206.39 , 332.75 , 251.77 ,
        17.95 , 265.77 ,  33.37 ,  62.4  ,  97.68 ,  57.05 ,  53.85 ,
        69.97 ,  48.5  ,  95.59 ,  94.18 ,  71.24 , 111.04 ,  30.58 ,
        77.95 , 151.93 ,  58.25 , 225.38 ,  64.08 , 130.09 ,  30.45 ,
       131.67 , 139.33 , 154.38 ,  30.16 , 131.91 , 177.8  , 116.31 ,
       138.32 , 179.5  , 131.67 ,  41.3  , 175.01 ,  49.32 , 119.88 ,
       185.54 ,  70.52 ,  65.5  ,  51.52 , 274.55 , 121.4  ,  84.23 ,
        86.26 ,  74.27 , 125.32 ,  41.17 , 118.9  , 293.55 , 301.78 ,
       113.17 , 113.01 , 101.08 ,  88.17 , 199.39 , 224.42 , 144.37 ,
       240.76 , 184.33 ,  41.91 , 168.55 ,  40.87 , 227.88 , 212.62 ,
       152.99 , 111.33 , 104.46 , 268.75 ,  37.82 , 116.19 , 139.36 ,
       290.79 , 126.28 ,  38.17 , 113.01 , 160.17 , 148.28 ,  80.12 ,
       199.95 , 224.81 ,  36.77 , 152.5  , 140.28 , 195.46 , 184.65 ,
        40.55 , 124.56 ,  32.35 ,  71.05 , 236.68 ,  60.44 , 139.36 ,
        50.38 ,  37.02 , 134.65 , 129.52 ,  55.68 ,  56.42 ,  57.03 ,
       227.6  ,  30.14 ,  97.15 , 169.03 ,  48.73 ,  31.7  , 177.24 ,
        58.99 ,  48.51 ,  74.86 , 263.65 ,  40.63 ,  94.72 ,  64.74 ,
        86.76 , 128.23 , 158.19 , 167.05 , 222.97 , 111.55 , 162.18 ,
        26.96 ,  42.54 , 263.02 ,  62.47 ,  48.66 , 192.15 ,  38.45 ,
       136.99 , 176.55 ,  47.12 , 163.95 , 100.55 ,  58.39 ,  51.91 ,
       134.89 , 189.65 ,  88.46 ,  55.72 ,  59.7  ,  73.12 , 315.96 ,
       184.65 ,  62.4  ,  72.23 ,  97.95 , 136.48 ,  43.47 , 314.3  ,
       126.64 , 233.68 ,  58.94 , 169.33 , 204.34 , 132.94 ,  66.52 ,
       231.69 ,  95.7  , 182.34 ,  66.19 ,  53.84 ,  47.88 ,  97.82 ,
       156.57 , 177.27 , 155.77 , 145.08 , 194.92 , 177.27 , 206.22 ,
       145.6  , 165.99 , 113.53 , 212.77 ,  35.19 , 144.14 , 109.66 ,
        90.9  , 188.69 ,  94.18 ,  38.7  , 116.36 , 115.03 ,  80.25 ,
       138.06 ,  34.74 ,  94.46 , 222.91 ,  99.28 , 169.41 ,  29.59 ,
        59.91 , 151.6  ,  84.22 , 213.76 ,  28.13 ,  46.91 ,  49.57 ,
        40.99 , 130.62 , 133.27 , 130.01 , 267.83 ,  61.44 , 104.29 ,
        58.39 , 125.64 , 156.17 , 112.67 ,  90.82 ,  72.21 ,  40.23 ,
        27.96 ,  89.48 , 169.29 , 102.76 , 118.75 ,  71.39 ,  33.85 ,
       137.52 ,  93.11 , 136.23 ,  71.63 , 117.93 , 217.33 ,  82.73 ,
       231.03 ,  96.05 , 121.305,  93.58 ,  67.03 ,  78.34 ,  99.18 ,
       227.88 ,  77.69 , 135.4  , 137.14 , 141.49 , 141.42 , 284.48 ,
        51.63 ,  26.39 , 129.16 ,  55.57 , 100.62 , 236.23 ,  74.27 ,
       115.02 , 107.4  , 247.33 ,  80.26 ,  55.68 ,  66.69 ,  62.46 ,
        40.91 ,  53.62 , 152.54 ,  86.8  , 110.17 , 180.99 , 146.63 ,
       212.77 , 132.89 ,  85.46 , 172.61 , 135.53 ,  39.35 ,  65.5  ,
        90.65 , 135.15 , 143.85 , 150.99 , 254.29 , 200.8  , 150.99 ,
       181.15 ,  98.48 , 152.55 ,  73.03 ,  55.   ,  19.14 , 130.9  ,
        74.32 ,  26.47 , 112.53 ,  22.5  ,  57.5  ,  45.68 , 124.61 ,
        28.82 ,  40.55 ,  92.15 , 308.8  ,  58.43 , 267.83 , 233.41 ,
        37.94 , 297.74 ,  24.89 , 134.755, 137.49 , 255.46 ,  26.6  ,
        35.5  ,  27.06 ,  30.58 ,  51.53 ,  82.25 , 144.95 ,  27.23 ,
       141.73 ,  69.43 , 120.5  , 112.03 , 153.54 ,  98.08 ,  67.77 ,
        17.77 , 212.77 , 320.89 ,  65.97 , 177.86 ,  33.74 , 126.64 ,
        92.71 , 127.84 , 213.76 ,  30.13 , 177.86 ,  21.5  ,  38.17 ,
       110.94 , 154.66 ,  34.51 , 205.26 ,  48.51 , 213.65 ,  23.71 ,
       107.67 ,  70.53 ,  68.38 ,  45.28 , 189.65 ,  70.45 ,  60.36 ,
       212.96 ,  33.44 , 233.19 ,  39.67 , 202.05 ,  61.93 ,  68.26 ,
        33.43 , 236.68 ,  93.81 , 116.74 , 227.06 , 169.03 , 191.16 ,
        47.84 ,  53.6  ,  83.64 , 126.28 ,  66.09 , 128.95 , 135.53 ,
       146.56 , 117.25 , 128.78 , 107.13 , 121.77 , 134.13 , 181.49 ,
       133.49 , 127.63 ,  81.58 , 171.09 ,  89.   ,  26.96 ,  93.86 ,
       177.29 , 159.49 ,  22.37 , 134.27 ,  92.71 , 169.03 , 112.48 ,
       253.45 , 107.91 , 115.54 , 171.6  , 175.41 , 155.11 ,  32.25 ,
        67.17 , 147.62 , 163.29 , 133.87 ,  93.02 , 113.58 , 190.75 ,
       349.24 ,  91.82 ,  99.19 , 186.4  , 129.39 ,  25.74 , 144.6  ,
        41.83 ,  44.01 ,  58.47 , 302.16 ,  94.92 ,  52.2  ,  73.53 ,
       245.65 , 157.63 , 158.09 , 296.24 ,  45.28 ,  55.   , 254.29 ,
       131.   ,  47.39 , 146.63 , 108.01 , 268.75 , 212.96 ,  60.44 ,
       133.06 , 136.99 ,  22.53 ,  88.17 ,  42.72 , 167.05 , 213.96 ,
        78.51 , 143.85 , 113.01 ,  30.14 ,  46.95 , 163.8  , 279.33 ,
       241.28 ,  53.96 ,  58.99 ,  28.   , 186.97 , 249.04 ,  74.41 ,
        70.93 , 116.24 ,  53.28 , 167.99 ,  78.49 , 121.91 , 102.07 ,
       151.08 , 118.41 ,  82.49 , 171.14 , 253.89 , 283.23 ,  91.99 ,
       155.22 , 297.74 ,  37.76 ,  33.07 , 185.9  ,  83.52 , 185.3  ,
       257.01 , 105.72 ,  85.91 ,  31.26 ,  74.86 , 146.63 , 133.87 ,
       115.03 , 247.23 ,  31.14 , 106.25 ,  77.3  ,  91.96 , 107.91 ,
       127.64 ,  70.88 ,  41.83 , 300.87 ,  36.56 , 154.66 , 156.86 ,
        29.8  ,  62.98 , 268.55 , 206.42 ,  26.9  ,  91.76 , 152.55 ,
        36.66 ,  62.07 ,  51.53 ,  48.21 ,  33.78 , 177.27 ,  64.46 ,
        35.23 ,  90.69 , 121.41 ,  56.2  , 284.09 , 167.12 ])

In [55]:
reg_model.score(X_train,y_train)

0.9997350937633047

In [56]:
reg_model.predict([[4428,3,4,0,0,1,0,0,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([190.4])

In [57]:
reg_model.predict([[3209,1,3,0,0,0,0,0,1,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([96.99])

In [58]:
reg_model.predict([[2688,1,3,0,0,0,1,0,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([124.49])

In [59]:
reg_model.predict([[3473,2,4,0,0,0,0,1,0,0,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([114.02])

In [60]:
X, y = make_regression(n_samples=100, n_features=5, noise=0.1, random_state=42)

model = LinearRegression()

# Define cross-validation strategy
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation
cv_scores = cross_val_score(model, X, y, cv=kf, scoring='r2')  # 'r2' for regression

# Display the results
print("Cross-Validation Scores (R^2):", cv_scores)
print("Mean R^2 Score:", np.mean(cv_scores))
print("Standard Deviation of R^2 Scores:", np.std(cv_scores))

Cross-Validation Scores (R^2): [0.99999944 0.99999958 0.99999954 0.99999952 0.9999994 ]
Mean R^2 Score: 0.9999994951564535
Standard Deviation of R^2 Scores: 6.758292405189928e-08

In [61]:


# Generate synthetic dataset (replace with your real estate dataset)
X, y = make_regression(n_samples=100, n_features=5, noise=0.1, random_state=42)

# Define the model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Define cross-validation strategy
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation
cv_scores = cross_val_score(rf_model, X, y, cv=kf, scoring='r2')  # 'r2' for regression

# Display results
print(f"R^2 Score for each fold: {cv_scores}")
print(f"Mean R^2 Score: {cv_scores.mean():.2f}")
print(f"Standard Deviation of R^2 Scores: {cv_scores.std():.2f}")

R^2 Score for each fold: [0.81623017 0.52052244 0.70495914 0.74947337 0.85752566]
Mean R^2 Score: 0.73
Standard Deviation of R^2 Scores: 0.12

In [62]:
# Generate a sample classification dataset
X, y = make_classification(n_samples=100, n_features=5, n_classes=2, random_state=42)

# Instantiate the model
model =  DecisionTreeRegressor()

# Use Stratified K-Fold for classification
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation for accuracy
accuracy_scores = cross_val_score(model, X, y, cv=skf, scoring='accuracy')

print(f"Accuracy for each fold: {accuracy_scores}")
print(f"Mean Accuracy: {accuracy_scores.mean():.2f}")
print(f"Standard Deviation of Accuracy: {accuracy_scores.std():.2f}")

Accuracy for each fold: [0.95 0.85 1.   0.85 1.  ]
Mean Accuracy: 0.93
Standard Deviation of Accuracy: 0.07

In [48]:
import pickle
with open('model3.pkl', 'wb') as f:
    pickle.dump(rf_model, f)